/* =========================================
   ALERT MODEL
========================================= */

const mongoose =
  require("mongoose");

/* =========================================
   ALERT SCHEMA
========================================= */

const alertSchema =
  new mongoose.Schema(

    {

      /* =========================
         ALERT MESSAGE
      ========================= */

      message: {

        type: String,

        required: true,

        trim: true,

      },

      title: {

        type: String,

        default: "System Alert",

      },

      /* =========================
         ALERT TYPE
      ========================= */

      type: {

        type: String,

        enum: [

          "Critical",
          "Warning",
          "Info",
          "Emergency"

        ],

        default: "Warning",

      },

      /* =========================
         PRIORITY
      ========================= */

      priority: {

        type: String,

        enum: [

          "Low",
          "Medium",
          "High",
          "Critical"

        ],

        default: "Medium",

      },

      /* =========================
         RELATED COMPLAINT
      ========================= */

      complaintId: {

        type:
          mongoose.Schema.Types.ObjectId,

        ref: "Complaint",

      },

      /* =========================
         TARGET USERS
      ========================= */

      targetRole: {

        type: String,

        enum: [

          "admin",
          "officer",
          "citizen",
          "all"

        ],

        default: "all",

      },

      /* =========================
         LOCATION
      ========================= */

      ward: {

        type: String,

        default: "Unknown",

      },

      location: {

        lat: {

          type: Number,

          default: 0,

        },

        lng: {

          type: Number,

          default: 0,

        }

      },

      /* =========================
         ALERT STATUS
      ========================= */

      read: {

        type: Boolean,

        default: false,

      },

      resolved: {

        type: Boolean,

        default: false,

      },

      resolvedBy: {

        type:
          mongoose.Schema.Types.ObjectId,

        ref: "User",

      },

      resolvedAt: {

        type: Date,

      },

      /* =========================
         ESCALATION
      ========================= */

      escalationLevel: {

        type: Number,

        default: 0,

      },

      autoGenerated: {

        type: Boolean,

        default: true,

      },

      /* =========================
         NOTIFICATION FLAGS
      ========================= */

      pushSent: {

        type: Boolean,

        default: false,

      },

      emailSent: {

        type: Boolean,

        default: false,

      },

      smsSent: {

        type: Boolean,

        default: false,

      }

    },

    {

      timestamps: true,

    }

  );

/* =========================================
   INDEXES
========================================= */

alertSchema.index({
  type: 1
});

alertSchema.index({
  priority: 1
});

alertSchema.index({
  targetRole: 1
});

alertSchema.index({
  read: 1
});

/* =========================================
   EXPORT MODEL
========================================= */

module.exports =
  mongoose.model(
    "Alert",
    alertSchema
  );